spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/faas?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
        username: root
        password: 1234
        driver-class-name: org.mariadb.jdbc.Driver

server:
  port: 18080

file:
    uploadDir: /Users/사용자/Pictures/sfviewer/ # 무조건 /로 끝내야 함.
    loadPath: /api/media
