server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true
  tomcat:
    accesslog:
      directory: log
      enabled: true
      file-date-format: .yyyy-MM-dd
      max-days: 14
      pattern: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i"' #combined
      prefix: access
      rotate: true
      suffix: .log
#    basedir: logs

spring:
  profiles:
    active: smartfarm

  servlet:
    multipart:
      max-file-size: 30MB # 최대 파일 사이즈
      max-request-size: 30MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true # sql log 보이게 설정
        format_sql: true

springdoc:
  version: 1.0.2
  api-docs:
    path: /api-docs
  swagger-ui:
    #    path: /api/swagger
    operations-sorter: method # method: HttpMethod 순으로 정렬, alpha: 알파벳 순으로 정렬
    syntax-highlight:
      activated: true
    tags-sorter: alpha # 태그 알파벳 순으로 정렬
    doc-expansion: none
    persist-authorization: true
    display-request-duration: true
  paths-to-match:
    - /api/**

file:
  uploadDir: /media/ # 무조건 /로 끝내야 함.
  loadPath: /api/media # 끝에 /를 안 붙여야 함

# 현재 13개
sensors: 농가번호,고유코드,수집시간,강우,풍속,풍향,대기온도,대기습도,태양광량,작물근접온도,작물대기습도,대지온도,대지수분함수율

jwt:
  paths: /api/v1, /api/v2, /api/v3
