
spring:
    config:
        activate:
            on-profile: prod
    datasource:
        url: jdbc:mariadb://39.112.10.37:23307/faas?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
        username: faas
        password: qweR1234@!
        driver-class-name: org.mariadb.jdbc.Driver
server:
    port: 15005
---
spring:
    config:
        activate:
            on-profile: smartfarm
    datasource:
        url: jdbc:mariadb://192.168.0.21:3307/faas?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
        username: faas
        password: qweR1234@!
        driver-class-name: org.mariadb.jdbc.Driver
server:
    port: 15005
---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        url: jdbc:mariadb://39.112.10.37:23307/faas?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
        username: faas
        password: qweR1234@!
        driver-class-name: org.mariadb.jdbc.Driver
server:
  port: 18080
---
server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true
  tomcat:
    accesslog:
      directory: log
      enabled: true
      file-date-format: .yyyy-MM-dd
      max-days: 14
      pattern: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i"' #combined
      prefix: access
      rotate: true
      suffix: .log
    basedir: ./logs

spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
      show-sql: true # sql log 보이게 설정
      hibernate:
          ddl-auto: update # ???? ?? ???(??? create??.)
logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    kr.co.jsol.mobileinfo: debug

jwt:
    secret: asdfbjahdslfjh2edoiughdivjhsxlkjvcahxclksdfhieduwhgowieurhgoeirufhsdlfddjvkahlsxckvjhasdlkjvchlkj34htop23i4uythoiuerwjhgasdvdgouasyv987d6v987
