spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
    hikari:
        maximum-pool-size: 50 # 커넥션 풀 50개 설정
        connection-timeout: 5000 # 커넥션 타임아웃 5초
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 11901
