jwt:
    secret: asdfbjahdslfjh2edoiughdivjhsxlkjvcahxclksdfhieduwhgowieurhgoeirufhsdlfddjvkahlsxckvjhasdlkjvchlkj34htop23i4uythoiuerwjhgasdvdgouasyv987d6v987
    paths: /swagger,login

tcp:
    server:
        port: 2332

ingsystem:
    message:
        length: 20
        delimiter: ','
        delimiter-count: 2
        default-delay: 60
        min-delay: 10 # 현재 최소 입력 값 10 초 (초단위)
        max-delay: 600 # 현재 최대 입력 값 10 분 (초단위)
        send-delay: 60 # 각 센서에 서버시간, 지연시간 보내는 주기 (초단위)

server:
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true
            force-response: true
    tomcat:
        accesslog:
            directory: log
            enabled: true
            file-date-format: .yyyy-MM-dd
            max-days: 14
            pattern: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i"' #combined
            prefix: access
            rotate: true
            suffix: .log
        threads:
            ## 쓰레드풀 공식 = CPU 수 * (CPU목표 사용량)*(1+대기 시간/서비스 시간)
            max: 200 # 쓰레드 사용할 최대 개수
            min-spare: 10 # 활성화 상태로 유지할 최소 쓰레드의 개수
    accept-count: 100 # 모든 스레드가 사용 중일때 들어오는 연결 요청 큐의 최대 길이
#    basedir: logs

spring:
    profiles:
        active: smartfarm
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show-sql: true # sql log 보이게 설정
                format_sql: true
    datasource:
        hikari:
            maximum-pool-size: 50 # 커넥션 풀 50개 설정
            connection-timeout: 5000 # 커넥션 타임아웃 5초
            idle-timeout: 600000 # 커넥션 유휴시간 10분
            max-lifetime: 1800000 # 커넥션 최대 생존시간 30분
            minimum-idle: 10 # 커넥션 최소 유휴 개수

file:
    uploadDir: /Users/사용자/Pictures/sfviewer/ # 무조건 /로 끝내야 함.
    loadPath: /api/media

sensors: 농가번호,고유코드,수집시간,강우,풍속,풍향,대기온도,대기습도,태양광량,작물근접온도,작물대기습도,대지온도,대지수분함수율

