spring:
    datasource:
        #        url: jdbc:mariadb://39.112.10.37:23307/faas?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
        #        username: faas
        #        password: qweR1234@!
        url: jdbc:mariadb://localhost:3306/faas?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
        username: root
        password: 1234
        driver-class-name: org.mariadb.jdbc.Driver

server:
    port: 18081

logging:
    level:
        com.zaxxer.hikari: TRACE
        com.zaxxer.hikari.HikariConfig: DEBUG

file:
    uploadDir: /Users/leeseongbok/Pictures/sfviewer/ # 무조건 /로 끝내야 함.
    loadPath: /api/media

sensors: 농가번호,고유코드,수집시간,강우,풍속,풍향,대기온도,대기습도,태양광량,작물근접온도,작물대기습도,대지온도,대지수분함수율
