spring:
    config:
        activate:
            on-profile: smartfarm
    datasource:
        url: jdbc:mariadb://192.168.0.21:3307/faas?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
        username: faas
        password: qweR1234@!
        driver-class-name: org.mariadb.jdbc.Driver
server:
    port: 15006
---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        url: jdbc:mariadb://39.112.10.37:23307/faas?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
        username: faas
        password: qweR1234@!
        driver-class-name: org.mariadb.jdbc.Driver
server:
    port: 18081
---
spring:
    config:
        activate:
            on-profile: local
    datasource:
        url: jdbc:mariadb://localhost:3306/faas?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
        username: root
        password: 1234
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: create
server:
    port: 18081
---
spring:
    config:
        activate:
            on-profile: common
jwt:
    secret: asdfbjahdslfjh2edoiughdivjhsxlkjvcahxclksdfhieduwhgowieurhgoeirufhsdlfddjvkahlsxckvjhasdlkjvchlkj34htop23i4uythoiuerwjhgasdvdgouasyv987d6v987

tcp:
    client:
        host: localhost
        port: 2332
    server:
        port: 2332

ingsystem:
    message:
        length: 20
        delimiter: ','
        delimiter-count: 3

---


server:
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true
            force-response: true
    tomcat:
        accesslog:
            directory: log
            enabled: true
            file-date-format: .yyyy-MM-dd
            max-days: 14
            pattern: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i"' #combined
            prefix: access
            rotate: true
            suffix: .log
#    basedir: logs

spring:
    profiles:
        active: local
        group:
            "local": "common"
            "dev": "common"
            "smartfarm": "common"
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher

    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                show-sql: true # sql log 보이게 설정
                format_sql: true

