spring:
    config:
        activate:
            on-profile: dev
    datasource:
#        url: jdbc:mariadb://39.112.10.37:23307/faas?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
        # 2024-10-17 IP 변경
        url: jdbc:mariadb://39.116.53.5:23307/faas?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
        username: faas
        password: qweR1234@!
        driver-class-name: org.mariadb.jdbc.Driver

server:
    port: 18081

sensors: 농가번호,고유코드,수집시간,강우,풍속,풍향,대기온도,대기습도,태양광량,작물근접온도,작물대기습도,대지온도,대지수분함수율
