spring:
    datasource:
        url: jdbc:mariadb://192.168.0.21:3307/faas?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
        username: faas
        password: qweR1234@!
        driver-class-name: org.mariadb.jdbc.Driver
        hikari:
            connection-timeout: 60000 # 커넥션 타임아웃 설정
            max-lifetime: 580000
            maximum-pool-size: 30 # 커넥션 풀 최대 풀 크기 설정
            idle-timeout: 10000 # 커넥션 풀 유휴 커넥션 설정
            validation-timeout: 10000
            minimum-idle: 5 # 커넥션 풀 최소 개수 설정

server:
    port: 15006

file:
    uploadDir: C:/jsolution/files/ # 무조건 /로 끝내야 함.
    loadPath: /api/media
